urls.py
from django.conf.urls import url, include
from django.contrib import admin
from apps.kasa import views

urlpatterns = [
    url(r'^$', views.kasa,name="kasa"),
    url(r'^download$', views.download,name="pobierz"),


#    url(r'^intranet/', views.load,name="intranet"),
]

models.py
from django.db import models
from django import forms

# Create your models here.
class plik(models.Model):
    description = models.CharField(max_length=255,blank=True,default="Plik")
    path = models.FileField(upload_to='./apps/kasa/pliki')
    uploaded_at = models.DateTimeField(auto_now_add=True)

class PlikDoPobrania(models.Model):
    name = models.CharField(max_length=255,blank=True,default="wywoz_tmp1.csv")
    path = models.FilePathField(path='./apps/kasa')

class fileform(forms.ModelForm):
    class Meta:
        model = plik
        fields = ('description','path',)

# Create your models here.

views.py
from django.shortcuts import render
from django.http import HttpResponse
from .models import fileform,PlikDoPobrania,plik
from .functions import readtxt
from django.conf import settings
from django.shortcuts import Http404
import os
# Create your views here.
def kasa(request, *args, **kwargs):
    url='kasa/kasa.html'
    context = {
    }

    if request.method == 'POST':
        myform = fileform(request.POST, request.FILES)
        if myform.is_valid():
            myplik = plik()
            myplik.description = myform.cleaned_data["description"]
            myplik.path = myform.cleaned_data["path"]
            print(myplik.path,myplik.description)
            myplik.save()
            kasa = readtxt(myplik)
            #intr = xls2intr(myplik)
    else:
        myform=fileform()
    myPlikDoPobrania = PlikDoPobrania()
    myPlikDoPobrania.save()
    return render(request,url,locals())




    return HttpResponse("222")
def download(request,path='apps/kasa/out.txt'):

    file_path = os.path.join(settings.MEDIA_ROOT, path)
    if os.path.exists(file_path):
        print(file_path)
        with open(file_path, 'rb') as fh:
            response = HttpResponse(fh.read(), content_type="application/vnd.ms-excel")
            response['Content-Disposition'] = 'inline; filename=' + os.path.basename(file_path)
            return response
    raise Http404

templates/kasa/base.html
{% load staticfiles %}
<!DOCTYPE html>
<html>

<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>test</title>
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/twitter-bootstrap/4.0.0/css/bootstrap.min.css">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
    <link rel="stylesheet" href="assets/css/Navigation-Clean.css">
    <link rel="stylesheet" href="assets/css/styles.css">
</head>

<body>
    <div>
<!--        <nav class="navbar navbar-light navbar-expand-md navigation-clean">
            <div class="container"><a class="navbar-brand" href="#">KASA</a><button class="navbar-toggler" data-toggle="collapse" data-target="#navcol-1"><span class="sr-only">Toggle navigation</span><span class="navbar-toggler-icon"></span></button>
                <div class="collapse navbar-collapse"
                    id="navcol-1">
                    <ul class="nav navbar-nav ml-auto">
                        <li class="nav-item" role="presentation"><a class="nav-link active" href="wywoz">Wywóz</a></li>
                        <li class="nav-item" role="presentation"><a class="nav-link" href="przywoz">Przywówz</a></li>
                    </ul>
                    <ul class="nav navbar-nav"></ul>
                </div>
            </div>
        </nav>-->
	{%block content %}
	{% endblock%}
    <div>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.2.1/jquery.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/twitter-bootstrap/4.0.0/js/bootstrap.bundle.min.js"></script>
</body>


</html>

templates/kasa/kasa.html
{% extends 'kasa/base.html' %}

{% block content %}

	
        <div class="container">
            <div class="intro">
                <h2 class="text-center">KASA IMPORT</h2>
                <p class="text-center">Plik kasa</p>
            </div>
            <form  name="form" method="POST" enctype="multipart/form-data" action=".">
		<div class="form-group">
		{% csrf_token %}
		<input id="id_path" class="form-control-file" type="file" name="path"></p>
		<input id="id_description" class="form-control-file" type="text" name="description"></div></p>
		<div class="form-group"><button class="btn btn-primary" type="submit">BROWSE</button></div>
            </form>
	{% if myplik.path %}
	<button class="btn" onclick="window.location.href='http://jan-svr-intra01:8000/kasa/download'"><i class="fa fa-download"></i> Download</button> 
	{% endif %}
        </div>


{% endblock %}